### ISSUE TITLE
removing these A) sections, if you want

### ISSUE THREAD

**Issue by stg7** [kloumpt/TUI_forschungsseminar_4K_paper#1]
so if you want to remove the section numbering with chars 
A) wonderful section

you need to replace:
```latex
\documentclass[conference]{IEEEtran}
```
with 
```latex
\documentclass[conference,compsoc]{IEEEtran}
```

**Comment by stg7** [comment]
or 
```latex
\documentclass[10pt,journal,compsoc]{IEEEtran}
```

**Comment by kloumpt** [comment]
Thanks, we are now using the conference+compsec configuration with 10pt fonts since the following commit:
[6b46d0b542bd84499b2a7f76534484ea81a7acb5](https://github.com/kloumpt/TUI_forschungsseminar_4K_paper/commit/6b46d0b542bd84499b2a7f76534484ea81a7acb5)
