### ISSUE TITLE
Fig12

### ISSUE THREAD

**Issue by stg7** [kloumpt/TUI_forschungsseminar_4K_paper#2]
you calculated the correlation using which measurement?
you are using: numpy.corrcoef that means: Pearson product-moment correlation coefficients (this should be mentioned in the text and figurecaption)
because there are a lot more correlation measurements

**Comment by kloumpt** [comment]
Thanks for the suggestion, the used correlation is now mentioned since the following commit:
[6b46d0b542bd84499b2a7f76534484ea81a7acb5](https://github.com/kloumpt/TUI_forschungsseminar_4K_paper/commit/6b46d0b542bd84499b2a7f76534484ea81a7acb5)
